
name: Initial setup
on: 
  create:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        echo "change made by action" > README.md
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Initial commit" -a
    - name: Push changes
      uses: garronej/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
